baseURL = "https://li-nuonuo.github.io/"
# åŸŸå
languageCode = "zh-cn"
# è¯­è¨€
title = "æ¢¨è¯ºçš„åšå®¢"
# æ ‡é¢˜
theme = 'github-style-master'
# ä¸»é¢˜
googleAnalytics = ""
# è°·æ­Œåˆ†æ
pygmentsCodeFences = true
# åˆ†åŒºä»£ç å›´æ 
pygmentsUseClasses = true
# åˆ†åŒºä½¿ç”¨ç±»

[params]
  author = "æ¢¨è¯º"
  # ä½œè€…
  description = "ä¸Šæµ·ç§‘æŠ€å¤§å­¦"
  # éšä¾¿è¯´å¥è¯
  github = "li-nuonuo"
#  facebook = ""
#  twitter = ""
#  linkedin = ""
#  instagram = ""
#  tumblr = ""
  email = "2029142041@qq.com"
  url = "https://li-nuonuo.github.io"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "ğŸ˜€"
  # å¯ç”¨emojiè¡¨æƒ…
  favicon = "/images/github.png"
  # ç½‘ç«™å›¾æ ‡
  location = "China,Shanghai"
  # å®šä½
  enableGitalk = true
  # ç¬¬ä¸‰æ–¹è¯„è®º
  [params.gitalk]
    clientID = "bf68a45bdf62b97ad98e" 
    clientSecret = "1695d059066c92b10bb251c0cc2185adf0409c45" 
    repo = "https://github.com/li-nuonuo/gitalk-linuo"
    owner = "li-nuonuo"
    admin = "li-nuonuo"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  [[params.links]]
    title = "Link"
    href = "https://github.com/li-nuonuo"
[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

